// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FilePriority } from "./FilePriority";

/**
 * Options for adding a .torrent: start paused, and optionally select file
 * priorities up front (sparse `(file index, priority)` pairs, default Normal).
 */
export type AddOptions = { paused: boolean, file_priorities: Array<[number, FilePriority]>, 
/**
 * Overrides the free space check performed before the download starts.
 */
skip_free_space_check: boolean, 
/**
 * Pause the torrent automatically once the download finishes, so it
 * does not keep seeding.
 */
stop_after_complete: boolean, };
