// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DhtStatus = { active: boolean, port: number, node_count: number, error: string | null, datagrams_received: bigint, datagrams_dropped: bigint, responses_sent: bigint, queries_sent: bigint, responses_rate_limited: bigint, transaction_timeouts: bigint, };
