// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FilePriority } from "./FilePriority";

export type FileStats = { path: string, length: number, priority: FilePriority, 
/**
 * Bytes of verified pieces that fall inside this file. Boundary pieces
 * count for every file they cover.
 */
verified_bytes: number, };
