// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FilePriority } from "./FilePriority";

/**
 * Options for adding a magnet. `pause_after_metadata` pauses the torrent as
 * soon as the metadata arrives, so the UI can show the file list and let the
 * user choose priorities before any data is downloaded.
 */
export type MagnetOptions = { paused: boolean, pause_after_metadata: boolean, file_priorities: Array<[number, FilePriority]>, };
