// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PeerDirection } from "./PeerDirection";

export type PeerStats = { addr: string, client: string, rate: number, up_rate: number, choked: boolean, unchoked: boolean, direction: PeerDirection, };
