// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileSummary } from "./FileSummary";
import type { PeerStats } from "./PeerStats";
import type { TrackerStatus } from "./TrackerStatus";

export type TorrentDetail = { id: string, info_hash: string, peers: Array<PeerStats>, files: Array<FileSummary>, trackers: Array<TrackerStatus>, comment: string | null, output_dir: string, session_uploaded: number, upload_rate: number, ratio: number, };
