// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { State } from "./State";

export type TorrentSummary = { id: string, name: string, state: State, total_length: number, verified_bytes: number, progress: number, download_rate: number, session_uploaded: number, upload_rate: number, ratio: number, eta_seconds: number | null, peer_count: number, output_dir: string, error: string | null, };
