// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TrackerState } from "./TrackerState";

export type TrackerStatus = { url: string, state: TrackerState, last_announce: number | null, seeders: number, leechers: number, last_error: string | null, };
