// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RemoteStatus = { running: boolean, connected: boolean, url: string | null, token: string, port: number, };
