// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Settings = { download_dir: string, listen_port: number, upload_limit_bps: number, dht_enabled: boolean, dht_port: number, remote_token: string, remote_port: number, };
