// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TorrentFileEntry } from "./TorrentFileEntry";

export type TorrentInspection = { name: string, total_length: number, files: Array<TorrentFileEntry>, };
